### ISSUE TITLE
[FEAT] 1차 세미나 실습 과제

### ISSUE THREAD

**Issue by geniusYoo** [NOW-SOPT-SERVER/geniusYoo#1]
## 구현 내용

- [ ] 은행 프로그램 설계

</br>

## Task

- [ ]  Enum 클래스 사용해보기
- [ ]  Interface 사용해서 SRP, OCP 적용해보기
